golf/config/routes.rb
Golf1::Application.routes.draw do
  resources :cities do
    collection do
      get 'get_cities_for_state'
    end
  end

  resources :states do
    collection do
      get 'get_states_for_country'
    end
  end

  resources :scores

  resources :scores do
    member do
      get 'sync_records'
    end
  end

  resources :groups do
    member do
      get 'add_group_to_game'
    end
  end

  get "welcome/index"

  resources :courses

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'welcome' => 'welcome#index',:as => :welcome

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  match "/application.manifest" => Rails::Offline

   root :to => "sessions#new"

end

golf/app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_one :game
end

golf/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.xml
  def index

	 @course = params[:course_id] if params[:course_id]
   @groups = Group.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.xml
  def show
    @group = Group.find(params[:id])
    @users = User.find(:all)
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.xml
  def new
    
    @group = Group.new
    @users = User.find(:all)
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
    @users = User.find(:all)
  end

  # POST /groups
  # POST /groups.xml
  def create
    @group = Group.new(params[:group])
    @group.user_id = self.current_user
		respond_to do |format|
      if @group.save
        format.html { redirect_to(groups_path, :notice => 'Group was successfully created.') }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.xml
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to(@group, :notice => 'Group was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  def add_group_to_game
    @group = Group.find(params[:id])
    @game = Game.new
		@game.course_id= params[:course_id]
    @game.group_id = @group.id
    @game.user_id = self.current_user.id
		@game.status = 1
    @game.save
    @get_players = Group.find(@game.group_id).users
    @get_course  = Course.find(@game.course_id).course_holes
		@get_players.each do |gp|
      @get_course.each do |gc|
        @score = Score.find_by_game_id_and_course_hole_id_and_user_id(@game.id,gc.id,gp.id) || Score.new
        @score.user_id = gp.id
        @score.course_hole_id = gc.id
        @score.game_id = @game.id
        @score.score =  0
        @score.save
      end
    end
    #if @game.save
    redirect_to(new_score_path(:game_id => @game.id))
      # format.xml  { render :xml => @group, :status => :created, :location => @group }
     # else
     #   format.html { render :action => "new" }
       # format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
    #end

  end

  # DELETE /groups/1
  # DELETE /groups/1.xml
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to(groups_url) }
      format.xml  { head :ok }
    end
  end
end

golf/app/helpers/groups_helper.rb
module GroupsHelper

def group_contains_user?(user)
    if @group
        @group.users.include?(user)
    else
        false
    end
end

end

golf/app/views/groups/_form.html.erb
<div id="header">
  <p class="leftalign">Define Course </p>
  <p class="rightalign"><%=  link_to_function "?" , "find_help()",:class =>"button", :id=>"help_button"%>&nbsp;<%= link_to_function 'Logout', 'logout_session()',:class => "button" %>&nbsp;&nbsp;<a id="online_status">status</a></p>
</div>
<div id="content">
      <h2 id="content_header">Create Group</h2>
    <div class="text_box_design">
  <%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
     <%= f.label :name %>&nbsp;<%= f.text_field :name, :placeholder=>"Group name"%>

    <fieldset>
      <legend>Select group members</legend>
        <% @users.each do |user| -%>
        <%= check_box_tag "group[user_ids][]",user.id, group_contains_user?(user) -%> <%= user.login -%><br />
        <%  end %>
    </fieldset>
  </div>
</div>
  </div>
<div id="footer">
  <p class="leftalign" ><%= link_to "Back", groups_path, :class =>"back_button" %></p>
  <p class="rightalign" ><%=  link_to_function "save", "check_group_field()", :class =>"button"%></p>
<% end %>
</div>

golf/app/views/groups/edit.html.erb
<%= render 'form' %>
<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

golf/app/views/groups/index.html.erb
<div id="header">
  <p class="leftalign">Define Game </p>
  <p class="rightalign"><%=  link_to_function "?" , "find_help()",:class =>"button", :id=>"help_button"%>&nbsp;<%= link_to_function 'Logout', 'logout_session()',:class => "button" %>&nbsp;&nbsp;<a id="online_status">status</a></p>
</div>
<div id="content">
  <div class="text_box_design">
    <table>
      <tr>
	<th>Select Group</th>
	<th></th>
      </tr>
      <% @groups.each do |group| %>
	<tr>
	  <td><%= group.name %></td>
	  <td><%= link_to 'Show', group %>
	    <% if @course %>
	      | <%= link_to 'Start Game',add_group_to_game_group_path(group,:course_id => @course) %></td>
	  <% end %>
	</tr>
      <% end %>
    </table>
  </div>
</div>
  <div id="footer">
    <p class="leftalign" ><%= link_to "Back",courses_path, {:class =>"back_button" } %></p>
    <p class="rightalign" ><%= link_to_function "New Group",'redirect_to_path("/groups/new")', { :class =>"button" } %></p>
  </div>

golf/app/views/groups/new.html.erb
<%= render 'form' %>

golf/app/views/groups/show.html.erb
<div id="header">
  <p class="leftalign">Define Course </p>
  <p class="rightalign"><%=  link_to_function "?" , "find_help()",:class =>"button", :id=>"help_button"%>&nbsp;<%= link_to_function 'Logout', 'logout_session()',:class => "button" %>&nbsp;&nbsp;<a id="online_status">status</a></p>
</div>
<div id="content">
  <div class="text_box_design">
    <h2 id="content_header"> Create new group </h2>
    <p id="notice"><%= notice %></p>
    <p>
      <b>Name:</b>
      <%= @group.name %>
       <fieldset>
         <legend>Group members</legend>
         <% @users.each do |user| -%>
            <%  if group_contains_user?(user) %>
	        <%= user.login -%>
            <%end%>
         <%  end %>
       </fieldset>
    </p>
  </div>
</div>
<div id="footer">
  <p class="leftalign " ><%= link_to 'Back', groups_path,{:class =>"back_button" } %> </p>
  <p class="rightalign " ><%= link_to 'Edit', edit_group_path(@group),{:class =>"button" } %> </p>
</div>