golf/config/routes.rb
Golf1::Application.routes.draw do
  resources :cities do
    collection do
      get 'get_cities_for_state'
    end
  end

  resources :states do
    collection do
      get 'get_states_for_country'
    end
  end

  resources :scores

  resources :scores do
    member do
      get 'sync_records'
    end
  end

  resources :groups do
    member do
      get 'add_group_to_game'
    end
  end

  get "welcome/index"

  resources :courses

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'welcome' => 'welcome#index',:as => :welcome

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  match "/application.manifest" => Rails::Offline

   root :to => "sessions#new"

end

golf/app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :user
  belongs_to :course_hole
end

golf/app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_filter :get_game_details ,:only => [:new,:create,:edit,:update]
  # GET /scores
  # GET /scores.xml
  def index
   @games = Game.played_by_current_user(self.current_user)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @scores }
    end
  end

  # GET /scores/1
  # GET /scores/1.xml
  def show
    @score = Score.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @score }
    end
  end

  # GET /scores/new
  # GET /scores/new.xml
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @score }
    end
  end

  # GET /scores/1/edit
  def edit
    @scores = Score.find_by_game_id(params[:game_id])
  end

  # POST /scores
  # POST /scores.xml
  def create
    @get_players.each do |gp|
      @get_course.each do |gc|
        @score = Score.find_by_game_id_and_course_hole_id_and_user_id(params[:game_id],gc.id,gp.id) || Score.new
        @score.user_id = gp.id
        @score.course_hole_id = gc.id
        @score.game_id = @selected_game.id
        @score.score = params[:score][gp.id.to_s.to_sym][gc.id.to_s.to_sym][0] ? params[:score][gp.id.to_s.to_sym][gc.id.to_s.to_sym][0] : 0
        @score.save
      end
    end
  
    redirect_to new_score_path(:game_id => @score.game_id)
    #@score = Score.new(params[:score])

   
  end

  # PUT /scores/1
  # PUT /scores/1.xml
  def update
    @score = Score.find(params[:id])

    respond_to do |format|
      if @score.update_attributes(params[:score])
        format.html { redirect_to(@score, :notice => 'Score was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @score.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.xml
  def destroy
    @score = Score.find(params[:id])
    @score.destroy

    respond_to do |format|
      format.html { redirect_to(scores_url) }
      format.xml  { head :ok }
    end
  end

  def sync_records
    game = params[:game].split(',')
    score = params[:score].split(',')
    i=0
    while i < score.length-1 do
        @score = Score.find(score[i].to_i)
        i+=1
        @score.score = score[i]
        i+=1
        @score.updated_at = game[1]
        @score.save
    end
    @game=Game.find(game[0].to_i)
    @game.updated_at = game[1]
    @game.save
  end

  private

  def get_game_details
    @selected_game = Game.find(params[:game_id]);
    @score=Score.find(:all,:conditions =>["game_id = ?",params[:game_id]]);
    @get_players = Group.find(@selected_game.group_id).users
    @get_course  = Course.find(@selected_game.course_id).course_holes
  end

end

golf/app/helpers/scores_helper.rb
module ScoresHelper
  def get_score(game,course,player)
     return Score.find_by_user_id_and_course_hole_id_and_game_id(player,course,game) ? Score.find_by_user_id_and_course_hole_id_and_game_id(player,course,game).score : 0
  end
end

golf/app/views/scores/_form.html.erb
<div id="score_table_design">
   <%= form_tag :action => 'create' do %>
 <table>
  <tr>
    <th rowspan="2">STROKE PLAY : <br /> Individaul HCP</th>
    <% @get_course.each do |gc| %>
     <th><b><%= gc.name %></b></th>
    <% end %>
   </tr>
  <tr>
    <% @get_course.each do |gc| %>
     <th>Par :<%= gc.par %></th>
    <% end %>
  </tr>
  <% @get_players.each do |gp| %>
  <tr>
    <td><%= gp.login.capitalize %></td>
    <% @get_course.each do |gc| %>
     <td><%=  text_field ("score["+gp.id.to_s+"]["+gc.id.to_s+"]").to_sym ,nil,:size => '7' %></td>
    <% end %>
  </tr>
  <%end%>

</table>
  <div class="actions">
    <%= hidden_field_tag :game_id,@selected_game.id%>
    <%= submit_tag 'Save' %>
  </div>
<% end %>
</div>

golf/app/views/scores/_old_form.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %><br />
    <%= f.text_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :course_hole_id %><br />
    <%= f.text_field :course_hole_id %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.text_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> 

golf/app/views/scores/edit.html.erb
<%= form_tag :action => 'update' do %>
<table border="1">
  <tr>
    <th rowspan="2">STROKE PLAY : <br /> Individaul HCP</th>
    <% @get_course.each do |gc| %>
     <th><b><%= gc.name %></b></th>
    <% end %>
   </tr>
  <tr>
    <% @get_course.each do |gc| %>
     <th>Par :<%= gc.par %></th>
    <% end %>
  </tr>
  <% @get_players.each do |gp| %>
  <tr>
    <td><%= gp.login.capitalize %></td>
    <% @get_course.each do |gc| %>
     <td><%=  text_field ("score["+gp.id.to_s+"]["+gc.id.to_s+"]").to_sym ,get_score(@selected_game.id,gc.id,gp.id),:size => '7' %></td>
    <% end %>
  </tr>
  <%end%>

</table>
  <div class="actions">
    <%= hidden_field_tag :game_id,@selected_game.id%>
    <%= submit_tag 'Save' %>
  </div>

<%= link_to 'Back', scores_path %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

golf/app/views/scores/index.html.erb
<div id="header">
  <p class="leftalign">Define Course </p>
  <p class="rightalign"><%=  link_to_function "?" , "find_help()",:class =>"button", :id=>"help_button"%>&nbsp;<%= link_to_function 'Logout', 'logout_session()',:class => "button" %>&nbsp;&nbsp;<a id="online_status">status</a></p>
</div>
<div id="content">
  <div class="text_box_design">
<table>
 <%if @games %>
  <tr>
    <th colspan="5">Games Played</th>
  </tr>
  <tr>
    <th>Join Id</th>
    <th>Name</th>
    <th>Status</th>
    <th>On</th>
    <th></th>
  </tr>
<% @games.each do |game| %>
  <tr>
    <td><%= game.id %></td>
    <td><%= game.course.name %></td>
    <td><%= game.status %></td>
    <td><%= game.created_at.strftime('%b %d, %Y') %></td>
    <td><%= link_to_function 'Scores',"new_score_show("+game.id.to_s+",'"+game.updated_at.to_s+"')" %></td>
  </tr>
 <% end %>
<%else%>
  <tr><th colspan="5">Sorry !!! No Games to Join</th></tr>
<%end%>
</table>
 </div>

</div>
<div id="footer">
  <p class="leftalign" ><%= link_to_function "Back","check_back_button('courses')", {:class =>"back_button" } %></p>
</div>

golf/app/views/scores/new.html.erb
<div id="header">
  <p class="leftalign">Score Card</p>
  <p class="rightalign"><%=  link_to_function "?" , "find_help()",:class =>"button", :id=>"help_button"%>&nbsp;<%= link_to_function 'Logout', 'logout_session()',:class => "button" %>&nbsp;&nbsp;<a id="online_status">status</a></p>
</div>
<div id="content">
<%= form_tag :action => 'create' do %>
<div id="score_table_header">
  <table cellpadding="0" cellspacing="0">
    <tr><th>STROKE-PLAY : </th></tr>
    <tr><th>Individual-HCP</th></tr>
    <% @get_players.each do |gp| %>
       <tr><td><%=link_to gp.login.capitalize,nil,{:class =>"player_button" }  %></td></tr>
    <%end%>
  </table>
</div>
<div id="score_table_content">
 <table cellpadding="0" cellspacing="0">
  <tr>
    <% @get_course.each do |gc| %>
       <th><%= gc.name %></th>
    <% end %>
   </tr>
  <tr>
    <% @get_course.each do |gc| %>
     <th>Par :<%= gc.par %></th>
    <% end %>
  </tr>

  <% @get_players.each do |gp| %>
  <tr>
    <% @get_course.each do |gc| %>
     <td><%=  text_field ("score["+gp.id.to_s+"]["+gc.id.to_s+"]").to_sym ,nil,{:value => get_score(@selected_game.id,gc.id,gp.id) ,:size => '7'} %></td>
    <% end %>
  </tr>
  <%end%>
</table>
</div>
</div>
<div id="footer">
  <%= hidden_field_tag :game_id,@selected_game.id%>
  <p class="leftalign" ><%= link_to "Back", scores_path, :class =>"back_button" %></p>
  <p class="rightalign" ><%= link_to_function "Save", "check_score_save()", :class =>"button",:id=>"score_save_id" %></p>
<% end %>
</div>

<script type="text/javascript">
  if(isOnline()){  
     db.transaction(
        function(tx){
                tx.executeSql('SELECT * from games where game_id=?',
                [<%=@selected_game.id%>],
                function(tx,results){
                  if(results.rows.length==0){
                    tx.executeSql('INSERT INTO GAMES(user_name,group_name,course_name,no_of_holes,course_id,user_id,group_id,game_id,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?);',
                    ['<%= @selected_game.user.login%>','<%=@selected_game.group.name%>','<%=@selected_game.course.name%>','<%=@selected_game.course.holes%>',<%=@selected_game.course_id%>,<%=@selected_game.user_id%>,<%=@selected_game.group_id%>,<%=@selected_game.id%>,<%=@selected_game.status%>,'<%=@selected_game.created_at %>','<%=@selected_game.updated_at %>']
                    );
                  }
            });
      });

     <%if @score %>
         db.transaction(
        function(tx) {
            tx.executeSql('SELECT * from score where game_id=?;',
            [<%=@selected_game.id%>],
            function(tx,results){
       <% @score.each do |s| %>
            
            if(results.rows.length == 0){
                    tx.executeSql('INSERT INTO SCORE(score_id,game_id,user_id,user_name,course_hole_id,par,score,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?);',
                    [<%=s.id%>,<%=s.game_id%>,<%=s.user_id%>,'<%=s.user.login%>',<%=s.course_hole_id%>,<%=s.course_hole.par%>,<%=s.score%>,'<%=s.created_at%>','<%=s.updated_at%>']
                  );
                }
            else{
                  tx.executeSql('UPDATE SCORE SET score=? WHERE score_id=?;',
                  [<%=s.score%>,<%=s.id%>]);
              }
       <% end %>
            }
            );
          });
     <% end %>
  }
</script>

golf/app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Game:</b>
  <%= @score.game_id %>
</p>

<p>
  <b>User:</b>
  <%= @score.user_id %>
</p>

<p>
  <b>Course hole:</b>
  <%= @score.course_hole_id %>
</p>

<p>
  <b>Score:</b>
  <%= @score.score %>
</p>


<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>