golf/config/routes.rb
Golf1::Application.routes.draw do
  resources :cities do
    collection do
      get 'get_cities_for_state'
    end
  end

  resources :states do
    collection do
      get 'get_states_for_country'
    end
  end

  resources :scores

  resources :scores do
    member do
      get 'sync_records'
    end
  end

  resources :groups do
    member do
      get 'add_group_to_game'
    end
  end

  get "welcome/index"

  resources :courses

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'welcome' => 'welcome#index',:as => :welcome

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  match "/application.manifest" => Rails::Offline

   root :to => "sessions#new"

end

golf/app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
  include Authentication
  include Authentication::ByPassword
  include Authentication::ByCookieToken
  has_and_belongs_to_many :groups
  belongs_to :country
  has_one :score
  has_one :game

  set_table_name 'users'

  validates :login, :presence   => true,
                    :uniqueness => true,
                    :length     => { :within => 3..40 },
                    :format     => { :with => Authentication.login_regex, :message => Authentication.bad_login_message }

  validates :first_name,  :format     => { :with => Authentication.name_regex, :message => Authentication.bad_name_message },
                    :length     => { :maximum => 100 },
                    :allow_nil  => true

  validates :email, :presence   => true,
                    :uniqueness => true,
                    :format     => { :with => Authentication.email_regex, :message => Authentication.bad_email_message },
                    :length     => { :within => 6..100 }

  

  # HACK HACK HACK -- how to do attr_accessible from here?
  # prevents a user from submitting a crafted form that bypasses activation
  # anything else you want your user to change should be added here.
  attr_accessible :login, :email, :first_name, :password, :password_confirmation,:country,:handicap,:gender,:privacy,:country_id,:last_name



  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  #
  # uff.  this is really an authorization, not authentication routine.
  # We really need a Dispatch Chain here or something.
  # This will also let us return a human error message.
  #
  def self.authenticate(login, password)
    return nil if login.blank? || password.blank?
    u = find_by_login(login.downcase) # need to get the salt
    u && u.authenticated?(password) ? u : nil
  end

  def login=(value)
    write_attribute :login, (value ? value.downcase : nil)
  end

  def email=(value)
    write_attribute :email, (value ? value.downcase : nil)
  end
end

golf/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Be sure to include AuthenticationSystem in Application Controller instead
  skip_before_filter :login_required
  before_filter :get_countries, :only=>[:create,:new]

  # render new.rhtml
  def new
    @user = User.new
  end
 
  def create
    logout_keeping_session!
    @user = User.new(params[:user])
    success = @user && @user.save
    if success && @user.errors.empty?
            # Protects against session fixation attacks, causes request forgery
      # protection if visitor resubmits an earlier form using back
      # button. Uncomment if you understand the tradeoffs.
      # reset session
      self.current_user = @user # !! now logged in
      redirect_back_or_default('/', :notice => "Thanks for signing up!  We're sending you an email with your activation code.")
    else
      flash.now[:error]  = "We couldn't set up that account, sorry.  Please try again, or contact an admin (link is above)."
      render :action => 'new'
    end
  end

end

golf/app/helpers/users_helper.rb
module UsersHelper
  
  #
  # Use this to wrap view elements that the user can't access.
  # !! Note: this is an *interface*, not *security* feature !!
  # You need to do all access control at the controller level.
  #
  # Example:
  # <%= if_authorized?(:index,   User)  do link_to('List all users', users_path) end %> |
  # <%= if_authorized?(:edit,    @user) do link_to('Edit this user', edit_user_path) end %> |
  # <%= if_authorized?(:destroy, @user) do link_to 'Destroy', @user, :confirm => 'Are you sure?', :method => :delete end %> 
  #
  #
  def if_authorized?(action, resource, &block)
    if authorized?(action, resource)
      yield action, resource
    end
  end

  #
  # Link to user's page ('users/1')
  #
  # By default, their login is used as link text and link title (tooltip)
  #
  # Takes options
  # * :content_text => 'Content text in place of user.login', escaped with
  #   the standard h() function.
  # * :content_method => :user_instance_method_to_call_for_content_text
  # * :title_method => :user_instance_method_to_call_for_title_attribute
  # * as well as link_to()'s standard options
  #
  # Examples:
  #   link_to_user @user
  #   # => <a href="/users/3" title="barmy">barmy</a>
  #
  #   # if you've added a .name attribute:
  #  content_tag :span, :class => :vcard do
  #    (link_to_user user, :class => 'fn n', :title_method => :login, :content_method => :name) +
  #          ': ' + (content_tag :span, user.email, :class => 'email')
  #   end
  #   # => <span class="vcard"><a href="/users/3" title="barmy" class="fn n">Cyril Fotheringay-Phipps</a>: <span class="email">barmy@blandings.com</span></span>
  #
  #   link_to_user @user, :content_text => 'Your user page'
  #   # => <a href="/users/3" title="barmy" class="nickname">Your user page</a>
  #
  def link_to_user(user, options={})
    raise "Invalid user" unless user
    options.reverse_merge! :content_method => :login, :title_method => :login, :class => :nickname
    content_text      = options.delete(:content_text)
    content_text    ||= user.send(options.delete(:content_method))
    options[:title] ||= user.send(options.delete(:title_method))
    link_to h(content_text), user_path(user), options
  end

  #
  # Link to login page using remote ip address as link content
  #
  # The :title (and thus, tooltip) is set to the IP address 
  #
  # Examples:
  #   link_to_login_with_IP
  #   # => <a href="/login" title="169.69.69.69">169.69.69.69</a>
  #
  #   link_to_login_with_IP :content_text => 'not signed in'
  #   # => <a href="/login" title="169.69.69.69">not signed in</a>
  #
  def link_to_login_with_IP content_text=nil, options={}
    ip_addr           = request.remote_ip
    content_text    ||= ip_addr
    options.reverse_merge! :title => ip_addr
    if tag = options.delete(:tag)
      content_tag tag, h(content_text), options
    else
      link_to h(content_text), login_path, options
    end
  end

  #
  # Link to the current user's page (using link_to_user) or to the login page
  # (using link_to_login_with_IP).
  #
  def link_to_current_user(options={})
    if current_user
      link_to_user current_user, options
    else
      content_text = options.delete(:content_text) || 'not signed in'
      # kill ignored options from link_to_user
      [:content_method, :title_method].each{|opt| options.delete(opt)} 
      link_to_login_with_IP content_text, options
    end
  end

end

golf/app/views/users/_user_bar.html.erb
<% if logged_in? -%>
  <div id="user-bar-greeting">Logged in as <%= link_to_current_user :content_method => :login %></div>
  <div id="user-bar-action"  >(<%= link_to "Log out", logout_path, { :title => "Log out" }    %>)</div>
<% else -%>
  <div id="user-bar-greeting"><%= link_to_login_with_IP 'Not logged in', :style => 'border: none;' %></div>
  <div id="user-bar-action"  ><%= link_to "Log in",  login_path,  { :title => "Log in" } %> /
                               <%= link_to "Sign up", signup_path, { :title => "Create an account" } %></div>
<% end -%>

golf/app/views/users/new.html.erb
<div id="header">
  <p class="leftalign">Register</p>
  <p class="rightalign"><%=  link_to_function "?" , "find_help()",:class =>"button", :id=>"help_button"%>&nbsp;&nbsp;<a id="online_status">status</a></p>
</div>
<div id="content">
    <% @user.password = @user.password_confirmation = nil %>
    <%= error_messages_for :user %>
    <%= form_for :user, :url => users_path do |f| -%>
     <table class="text_box_design" id="main_container">
       <tr><td><%= f.text_field :first_name ,:placeholder => 'First name'%></td></tr>
       <tr><td><%= f.text_field :last_name ,:placeholder => 'Last name'%></td></tr>
       <tr><td><%= f.text_field :email ,:placeholder => 'Email'%></td></tr>
       <tr><td><%= f.text_field :login ,:placeholder => 'Username'%></td></tr>
       <tr><td><%= f.select(:country_id,get_dropdown_options(@countries),{},{:class=>'dropdown'})%></td></tr>
       <tr><td><%= f.text_field :handicap ,:placeholder => 'Handicap'%></td></tr>
       <tr><td><%= f.select(:gender,[['Select Gender',true],['Male',true],['Female',false]],{},{:class=>'dropdown'}) %></td></tr>
       <tr><td><%= f.select(:privacy,[['Select Privacy',false],['Public',false],['Private',true]],{},{:class=>'dropdown'}) %></td></tr>
       <tr><td><%= f.password_field :password ,:placeholder => 'Password'%></td></tr>
       <tr><td><%= f.password_field :password_confirmation ,:placeholder => 'Re-Enter Password'%></td></tr>
       <tr><td><%= label_tag(:terms ,"I Accept to the terms and conditions")%> <%= select_tag(:terms,options_for_select([['No',1],['Yes',2]],1))%></td></tr>
     </table>
  <div id="help_info" class="align_content_screen text_box_design hidden">
     <p>
       <h2>Register</h2>
       <h4>  To use GameBook you needs to register for a <b> free </b> <b>Register</b> account.<br/> Please provide your first and last names,a valid email address and a unique username,<br />select your home country, enter your exact handicap,<br />select your gender and the privacy setting.<br />  <b> Public </b> profiles are open for everyone to see, and to -for example - link people to your online scorecards at www.golfgamebook.com.<br /> <b> Private </b> profiles are only available to your GameBook friends. if you meet on the course before the game,<br /> private profiles can be trickly to pair up in a game.Be bold-be public! <br/>  type your password and re-enter for confirmation and select your for accept Terms and Condition. </h4>
     </p>
   </div>
 </div>
<div id="footer">
  <p class="leftalign" ><%= link_to "Back",login_path, {:class =>"back_button" } %></p>
  <p class="rightalign" ><%= f.submit 'Done',:class => 'hide_save_button'%><%= link_to_function "Save","validate_new_user()",:class =>"button"%></p>
<% end -%>
</div>